# Generated by Django 5.1.4 on 2024-12-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailthread',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='emailthread',
            name='customer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
