# Generated by Django 5.1.4 on 2024-12-26 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_emailthread_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailthread',
            unique_together={('staff', 'customer_name')},
        ),
    ]
