# Generated by Django 5.1.4 on 2025-01-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pandsdocument_alter_emailthread_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandsdocument',
            name='last_upserted',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
