# Generated by Django 5.1.4 on 2025-01-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rephrasehistory_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rephrasehistory',
            name='history',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rephrasehistory',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rephrase_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
